server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: stratus
    static_configs:
      - targets:
          - localhost
        labels:
          job: stratus
          __path__: /var/log/host/stratus.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            caller: caller
            error: error
            trace_id: trace_id
            span_id: span_id
      - labels:
          level:
          caller:
          error:
          trace_id:
          span_id:
      - output:
          source: message