version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"

    pull-request-branch-name:
      separator: "-"
    
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    
    labels:
      - "dependencies"
      - "rust"
      - "dependabot"

    commit-message:
      prefix: "deps"
      include: "scope"
