[package]
name = "stratus"
version = "0.1.0"
edition = "2021"
default-run = "stratus"

# ------------------------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------------------------

[dependencies]

# stdx
anyhow = "1.0.79"
async-trait = "0.1.77"
chrono = "0.4.31"
clap = { version = "4.4.18", features = ["derive", "env"] }
const_format = "0.2.32"
const-hex = "1.10.0"
csv = "1.3.0"
derive_more = "0.99.17"
derive-new = "0.6.0"
hex-literal = "0.4.1"
indexmap = { version = "2.2.5", features = ["serde"] }
itertools = "0.12.0"
nonempty = { version = "0.10.0", features = ["serialize"] }
paste = "1.0.14"
phf = "0.11.2"
pin-project = "1.1.3"
quote = "1.0.33"
rand = "0.8.5"
strum = "0.25.0"
thiserror = "1.0.56"
url = "2.5.0"

# async
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
tokio-util = "0.7.10"

# serialization
serde = "1.0.193"
serde_json = "1.0.108"
serde_with = "3.5.1"

# parallelism
crossbeam-channel = "0.5.11"
futures = "0.3.30"

# ethereum / rpc
ethabi = "18.0.0"
ethereum-types = "0.14.1"
ethers-core = "2.0.11"
keccak-hasher = "0.15.0" # this version must be compatible with triehash
rlp = "0.5.2"
revm = "7.1.0"
triehash = "0.8.4"

# network
jsonrpsee = { version = "0.21.0", features = ["server", "client"] }
reqwest = { version = "0.11.24", features = ["json"] }
tower = "0.4.13"

# observability
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }

# storage
sled = "0.34.7"
sqlx = { version = "0.7.3", features = ["runtime-tokio", "postgres", "bigdecimal", "time"] }
num-traits = "0.2.18"

# containers
testcontainers = "0.15.0"
testcontainers-modules = { version = "0.3.5", features = ["postgres"] }

# test
fake = { version = "2.9.2", features = ["derive"] }

[dev-dependencies]
binary_macros = "1.0.0"
fancy-duration = "0.9.2"
serial_test = "2.0.0"
stringreader = "0.1.1"

[build-dependencies]
const-hex = "1.10.0"
glob = "0.3.1"
nom = "7.1.3"
phf_codegen = "0.11.2"

# ------------------------------------------------------------------------------
# Binaries
# ------------------------------------------------------------------------------

[[bin]]
name = "rpc-downloader"
path = "src/bin/rpc_downloader.rs"

[[bin]]
name = "importer-offline"
path = "src/bin/importer_offline.rs"

[[bin]]
name = "importer-online"
path = "src/bin/importer_online.rs"

[[bin]]
name = "state-validator"
path = "src/bin/state_validator.rs"

# ------------------------------------------------------------------------------
# Lints
# ------------------------------------------------------------------------------

[lints.clippy]
clone_on_ref_ptr = "warn"
disallowed_names = "warn"
manual_let_else = "warn"
semicolon_if_nothing_returned = "warn"

# ------------------------------------------------------------------------------
# Features
# ------------------------------------------------------------------------------

[features]
default = []
dev  = []  # Application is running in develoment mode.
perf = []  # Application is running in performance test mode.
