[package]
name = "stratus"
version = "0.1.0"
edition = "2021"

# ------------------------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------------------------

[dependencies]

# stdx
anyhow = "1.0.79"
async-trait = "0.1.77"
chrono = "0.4.31"
clap = { version = "4.4.18", features = ["derive", "env"] }
const-hex = "1.10.0"
derive_more = "0.99.17"
derive-new = "0.6.0"
hex-literal = "0.4.1"
indexmap = "2.1.0"
itertools = "0.12.0"
nonempty = "0.9.0"
paste = "1.0.14"
phf = "0.11.2"
pin-project = "1.1.3"
quote = "1.0.33"
strum = "0.25.0"
thiserror = "1.0.56"

# async
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
tokio-util = "0.7.10"

# serialization
serde = "1.0.193"
serde_json = "1.0.108"
serde_with = "3.5.1"

# parallelism
crossbeam-channel = "0.5.11"
futures = "0.3.30"

# ethereum / rpc
ethabi = "18.0.0"
ethereum-types = "0.14.1"
ethers-core = "2.0.11"
keccak-hasher = "0.15.0" # this version must be compatible with triehash
rlp = "0.5.2"
revm = "3.5.0"
triehash = "0.8.4"

# network
jsonrpsee = { version = "0.21.0", features = ["server", "client"] }
tower = "0.4.13"

# observability
metrics = "0.21.1"
metrics-exporter-prometheus = "0.12.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }

# storage
sqlx = { version = "0.7.3", features = ["runtime-tokio", "postgres", "bigdecimal", "time"] }

# test
fake = { version = "2.9.2", features = ["derive"] }

[dev-dependencies]
binary_macros = "1.0.0"
serial_test = "2.0.0"
stringreader = "0.1.1"

[build-dependencies]
const-hex = "1.10.0"
glob = "0.3.1"
nom = "7.1.3"
phf_codegen = "0.11.2"

# ------------------------------------------------------------------------------
# Binaries
# ------------------------------------------------------------------------------

[[bin]]
name = "task-get-blocks"
path = "src/bin/task-get-blocks.rs"

[[bin]]
name = "rpc-server-poller"
path = "src/bin/rpc_server_poller.rs"

# ------------------------------------------------------------------------------
# Lints
# ------------------------------------------------------------------------------

[lints.clippy]
clone_on_ref_ptr = "warn"
disallowed_names = "warn"
manual_let_else = "warn"
semicolon_if_nothing_returned = "warn"
