[package]
name = "stratus"
version = "0.1.0"
edition = "2021"
default-run = "stratus"

# ------------------------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------------------------

[dependencies]

# stdx
anyhow = "=1.0.82"
async-trait = "=0.1.80"
byte-unit = "=5.1.4"
chrono = "=0.4.38"
const_format = "=0.2.32"
const-hex = "=1.10.0"
csv = "=1.3.0"
derive_more = "=0.99.17"
derive-new = "=0.6.0"
hex-literal = "=0.4.1"
indexmap = { version = "=2.2.6", features = ["serde"] }
itertools = "=0.12.1"
nonempty = { version = "=0.10.0", features = ["serialize"] }
paste = "=1.0.14"
phf = "=0.11.2"
pin-project = "=1.1.5"
quote = "=1.0.36"
rand = "=0.8.5"
strum = "=0.26.2"
thiserror = "=1.0.59"
url = "=2.5.0"

# async
tokio = { version = "=1.37.0", features = ["rt-multi-thread", "macros", "signal"] }
tokio-util = "=0.7.10"

# config
clap = { version = "=4.5.4", features = ["derive", "env"] }
dotenvy = "=0.15.7"

# serialization
serde = "=1.0.199"
serde_json = "=1.0.116"
serde_with = "=3.8.1"

# parallelism
crossbeam-channel = "=0.5.12"
futures = "=0.3.30"
futures-timer = "=3.0.3"
futures-util = "=0.3.30"

# ethereum / rpc
ethabi = "=18.0.0"
ethereum-types = "=0.14.1"
ethers-core = "=2.0.14"
evm-disassembler = "=0.5.0"
keccak-hasher = "=0.15.3" # this version must be compatible with triehash
revm = { version = "=8.0.0", features = ["asm-keccak"] }
rlp = "=0.5.2"
triehash = "=0.8.4"


# network
jsonrpsee = { version = "=0.22.4", features = ["server", "client"] }
reqwest = { version = "=0.12.4", features = ["json"] }
tower = "=0.4.13"

# observability
metrics = { version = "=0.22.3", optional = true }
metrics-exporter-prometheus = { version = "=0.14.0", optional = true }
tracing = { version = "=0.1.40", features = ["attributes"] }
tracing-subscriber = { version = "=0.3.18", features = ["env-filter", "json"] }
tracing-opentelemetry = "=0.23.0"
sentry = "=0.32.3"
opentelemetry = "=0.22.0"
opentelemetry-otlp = "=0.15.0"
opentelemetry_sdk = { version = "=0.22.1", features = ["rt-tokio"] }


# storage
sqlx = { version = "=0.7.4", features = ["runtime-tokio", "postgres", "bigdecimal", "time"] }
num-traits = "=0.2.18"
rocksdb = { version = "=0.22.0", features = ["multi-threaded-cf"], optional = true }
kube = { version = "=0.90.0", optional = true, features = ["runtime", "derive"] }
k8s-openapi = { version = "=0.21.1", optional = true, features = ["latest"] }
bincode = { version = "=1.3.3", optional = true }

# containers
testcontainers = "=0.15.0"
testcontainers-modules = { version = "=0.3.5", features = ["postgres"] }

# test
fake = { version = "=2.9.2", features = ["derive"] }

[dev-dependencies]
binary_macros = "=1.0.0"
fancy-duration = "=0.9.2"
stringreader = "=0.1.1"

[build-dependencies]
const-hex = "=1.10.0"
glob = "=0.3.1"
nom = "=7.1.3"
phf_codegen = "=0.11.2"

# ------------------------------------------------------------------------------
# Binaries
# ------------------------------------------------------------------------------

[[bin]]
name = "rpc-downloader"
path = "src/bin/rpc_downloader.rs"

[[bin]]
name = "importer-offline"
path = "src/bin/importer_offline.rs"

[[bin]]
name = "importer-online"
path = "src/bin/importer_online.rs"

[[bin]]
name = "state-validator"
path = "src/bin/state_validator.rs"

[[bin]]
name = "run-with-importer"
path = "src/bin/run_with_importer.rs"

# ------------------------------------------------------------------------------
# Features
# ------------------------------------------------------------------------------

[features]
default = []

# Application is running in develoment mode.
dev  = []

# Application is running in performance test mode.
perf = []

# Enable prefetching slots during EVM execution.
evm-slot-prefetch = []

# Enable metrics dependencies and code for metrics collection.
metrics = ["dep:metrics", "dep:metrics-exporter-prometheus"]

# Enable RocksDB dependencies.
rocks = ["rocksdb", "bincode", "kube", "k8s-openapi"]

# ------------------------------------------------------------------------------
# Lints
# ------------------------------------------------------------------------------

[lints.clippy]
clone_on_ref_ptr = "warn"
disallowed_names = "warn"
manual_let_else = "warn"
semicolon_if_nothing_returned = "warn"
