apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: stratus
  description: An EVM-compatible blockchain providing an EVM executor and JSON-RPC server, with RocksDB for custom storage
  annotations:
    github.com/project-slug: cloudwalk/stratus
    backstage.io/techdocs-ref: dir:.
    sentry/application-name: stratus
    opentelemetry/application-name: stratus
    prometheus/application-name: stratus
    grafana/dashboard-selector: stratus
    grafana/alert-label-selector: service=stratus
  labels:
    cloudwalk.io/regulation-scope: none
    cloudwalk.io/critical-level: high
  tags:
    - rust
    - blockchain
    - evm
  links:
    - url: https://github.com/cloudwalk/stratus
      title: Repository
      icon: github
    - url: https://grafana.cloudwalk.network/d/fc5870d5-2b1d-4873-ab64-080d025df0eb/stratus-general
      title: Application Metrics
      icon: dashboard
    - url: https://grafana.cloudwalk.network/d/rYdddlPWk2/node-exporter
      title: VM Metrics
      icon: dashboard
spec:
  type: service
  system: Ledger
  lifecycle: production
  owner: team-ledger
