version: "2"
services:

  # ----------------------------------------------------------------------------
  # PostgreSQL
  # ----------------------------------------------------------------------------
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: stratus
    ports:
      - 5432:5432
    volumes:
      - "./static/schema/001-schema-external-rpc.sql:/docker-entrypoint-initdb.d/001-schema.sql"

  postgres-persistent:
    extends:
      service: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    profiles:
      - manual

  # ----------------------------------------------------------------------------
  # Redis
  # ----------------------------------------------------------------------------
  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
    - REDIS_HOSTS=local:redis:6379

  # ----------------------------------------------------------------------------
  # PromethMeus
  # ----------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus
    volumes:
      - ./static/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--log.level=debug"

  # ----------------------------------------------------------------------------
  # OpenTelemetry
  # ----------------------------------------------------------------------------
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - 4317:4317
      - 16686:16686

volumes:
  postgres-data:
