version: "2"
services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: stratus
    ports:
      - 5432:5432
    volumes:
      - "./static/schema/001-init.sql:/docker-entrypoint-initdb.d/001-schema.sql"
      - "./static/schema/002-schema-external-rpc.sql:/docker-entrypoint-initdb.d/002-schema.sql"
      - "./static/schema/003-triggers-and-procedures.sql:/docker-entrypoint-initdb.d/003-triggers-and-procedures.sql"
    command:
      - postgres
      - --log_statement=all
      - --log_min_duration_statement=0
      - --log_statement_stats=on
      - --shared_preload_libraries=pg_stat_statements
      - --pg_stat_statements.track=all

  postgres-persistent:
    extends:
      service: postgres
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    profiles:
      - manual

  prometheus:
    image: prom/prometheus
    volumes:
      - ./static/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--log.level=debug"

volumes:
  postgres-data:
