version: "2"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: stratus
    ports:
      - 5432:5432
    volumes:
      - "./static/schema/001-init.sql:/docker-entrypoint-initdb.d/001-schema.sql"
      - "./static/schema/002-schema-external-rpc.sql:/docker-entrypoint-initdb.d/002-schema.sql"