pub mod external;
mod transaction_dag;

use std::collections::HashSet;

pub use external::ExternalRelayer;
pub use external::ExternalRelayerClient;
use lazy_static::lazy_static;

lazy_static! {
    static ref SIGNATURES: HashSet<&'static str> = [
        "PixCashier",
        "PixCashierv3",
        "CardPaymentProcessor",
        "CardPaymentProcessorv2",
        "CompoundAgent",
        // "BRLCToken::freeze(address,uint256)",
        // "BRLCToken::transferFrozen(address,address,uint256)",
        // "BRLCToken::restrictionIncrease(address,bytes32,uint256)",
        // "BRLCToken::restrictionDecrease(address,bytes32,uint256)",
        // "BRLCToken::blocklist(address)",
        // "BRLCToken::unBlocklist(address)",
        // "BRLCToken::blacklist(address)",
        // "BRLCToken::unBlacklist(address)",
    ]
    .into_iter()
    .collect();
}

lazy_static! {
    static ref UNRESIGNABLE_FUNCTIONS: HashSet<&'static str> = [
        "BRLCToken::_isInitializing",
        "BRLCToken::__Context_init",
        "BRLCToken::__Context_init_unchained",
        "BRLCToken::_msgSender",
        "BRLCToken::__Ownable_init",
        "BRLCToken::__Ownable_init_unchained",
        "BRLCToken::renounceOwnership",
        "BRLCToken::transferOwnership",
        "BRLCToken::__Pausable_init",
        "BRLCToken::__Pausable_init_unchained",
        "BRLCToken::__ERC20_init",
        "BRLCToken::__ERC20_init_unchained",
        "BRLCToken::__Blocklistable_init",
        "BRLCToken::__Blocklistable_init_unchained",
        "BRLCToken::enableBlocklist",
        "BRLCToken::setMainBlocklister",
        "BRLCToken::configureBlocklister",
        "BRLCToken::__PausableExt_init",
        "BRLCToken::__PausableExt_init_unchained",
        "BRLCToken::pause",
        "BRLCToken::unpause",
        "BRLCToken::setPauser",
        "BRLCToken::__Rescuable_init",
        "BRLCToken::__Rescuable_init_unchained",
        "BRLCToken::setRescuer",
        "BRLCToken::__ERC20Base_init",
        "BRLCToken::__ERC20Base_init_unchained",
        "BRLCToken::__ERC20Freezable_init",
        "BRLCToken::__ERC20Freezable_init_unchained",
        "BRLCToken::__ERC20Hookable_init",
        "BRLCToken::__ERC20Hookable_init_unchained",
        "BRLCToken::setBeforeTokenTransferHooks",
        "BRLCToken::setAfterTokenTransferHooks",
        "BRLCToken::__ERC20Mintable_init",
        "BRLCToken::__ERC20Mintable_init_unchained",
        "BRLCToken::updateMainMinter",
        "BRLCToken::configureMinter",
        "BRLCToken::removeMinter",
        "BRLCToken::configureMaxPendingPremintsCount",
        "BRLCToken::__ERC20Restrictable_init",
        "BRLCToken::__ERC20Restrictable_init_unchained",
        "BRLCToken::assignPurposes",
        "BRLCToken::__ERC20Trustable_init",
        "BRLCToken::__ERC20Trustable_init_unchained",
        "BRLCToken::configureTrustedAccount",
        "BRLCToken::__CWToken_init",
        "BRLCToken::__CWToken_init_unchained",
        "BRLCToken::__BRLCToken_init",
        "BRLCToken::__BRLCToken_init_unchained",
        "CardPaymentProcessorv2::_isInitializing",
        "CardPaymentProcessorv2::__Context_init",
        "CardPaymentProcessorv2::__Context_init_unchained",
        "CardPaymentProcessorv2::_msgSender",
        "CardPaymentProcessorv2::__ERC165_init",
        "CardPaymentProcessorv2::__ERC165_init_unchained",
        "CardPaymentProcessorv2::__AccessControl_init",
        "CardPaymentProcessorv2::__AccessControl_init_unchained",
        "CardPaymentProcessorv2::grantRole",
        "CardPaymentProcessorv2::revokeRole",
        "CardPaymentProcessorv2::__Pausable_init",
        "CardPaymentProcessorv2::__Pausable_init_unchained",
        "CardPaymentProcessorv2::__AccessControlExt_init",
        "CardPaymentProcessorv2::__AccessControlExt_init_unchained",
        "CardPaymentProcessorv2::grantRoleBatch",
        "CardPaymentProcessorv2::revokeRoleBatch",
        "CardPaymentProcessorv2::__Blocklistable_init",
        "CardPaymentProcessorv2::__Blocklistable_init_unchained",
        "CardPaymentProcessorv2::__PausableExt_init",
        "CardPaymentProcessorv2::__PausableExt_init_unchained",
        "CardPaymentProcessorv2::__Rescuable_init",
        "CardPaymentProcessorv2::__Rescuable_init_unchained",
        "CardPaymentProcessorv2::__CardPaymentProcessor_init",
        "CardPaymentProcessorv2::__CardPaymentProcessor_init_unchained",
        "CompoundAgent::_isInitializing",
        "CompoundAgent::__Context_init",
        "CompoundAgent::__Context_init_unchained",
        "CompoundAgent::_msgSender",
        "CompoundAgent::__Ownable_init",
        "CompoundAgent::__Ownable_init_unchained",
        "CompoundAgent::renounceOwnership",
        "CompoundAgent::transferOwnership",
        "CompoundAgent::__Pausable_init",
        "CompoundAgent::__Pausable_init_unchained",
        "CompoundAgent::__PausableExt_init",
        "CompoundAgent::__PausableExt_init_unchained",
        "CompoundAgent::pause",
        "CompoundAgent::unpause",
        "CompoundAgent::setPauser",
        "CompoundAgent::__CompoundAgent_init",
        "CompoundAgent::__CompoundAgent_init_unchained",
        "CompoundAgent::mint",
        "CompoundAgent::redeem",
        "CompoundAgent::redeemUnderlying",
        "CompoundAgent::repayTrustedBorrow",
        "CompoundAgent::repayTrustedBorrows",
        "CompoundAgent::mintAndRepayTrustedBorrow",
        "CompoundAgent::mintAndRepayTrustedBorrows",
        "CompoundAgent::mintOnDebtCollection",
        "CompoundAgent::redeemAndBurn",
        "CompoundAgent::configureAdmin",
        "CompoundAgent::setMintOnDebtCollectionCap",
        "CompoundAgent::transferOwnership",
        "PixCashierv2::_isInitializing",
        "PixCashierv2::__Context_init",
        "PixCashierv2::__Context_init_unchained",
        "PixCashierv2::_msgSender",
        "PixCashierv2::__ERC165_init",
        "PixCashierv2::__ERC165_init_unchained",
        "PixCashierv2::__AccessControl_init",
        "PixCashierv2::__AccessControl_init_unchained",
        "PixCashierv2::grantRole",
        "PixCashierv2::revokeRole",
        "PixCashierv2::__Pausable_init",
        "PixCashierv2::__Pausable_init_unchained",
        "PixCashierv2::__AccessControlExt_init",
        "PixCashierv2::__AccessControlExt_init_unchained",
        "PixCashierv2::grantRoleBatch",
        "PixCashierv2::revokeRoleBatch",
        "PixCashierv2::__Blocklistable_init",
        "PixCashierv2::__Blocklistable_init_unchained",
        "PixCashierv2::__PausableExt_init",
        "PixCashierv2::__PausableExt_init_unchained",
        "PixCashierv2::__Rescuable_init",
        "PixCashierv2::__Rescuable_init_unchained",
        "PixCashierv2::initialize",
        "PixCashierv2::__PixCashier_init",
        "PixCashierv2::__PixCashier_init_unchained",
        "PixCashierv3::_checkInitializing",
        "PixCashierv3::_isInitializing",
        "PixCashierv3::__Context_init",
        "PixCashierv3::__Context_init_unchained",
        "PixCashierv3::_msgSender",
        "PixCashierv3::__ERC165_init",
        "PixCashierv3::__ERC165_init_unchained",
        "PixCashierv3::__AccessControl_init",
        "PixCashierv3::__AccessControl_init_unchained",
        "PixCashierv3::grantRole",
        "PixCashierv3::revokeRole",
        "PixCashierv3::__UUPSUpgradeable_init",
        "PixCashierv3::__UUPSUpgradeable_init_unchained",
        "PixCashierv3::upgradeToAndCall",
        "PixCashierv3::_checkProxy",
        "PixCashierv3::_authorizeUpgrade",
        "PixCashierv3::__Pausable_init",
        "PixCashierv3::__Pausable_init_unchained",
        "PixCashierv3::__AccessControlExt_init",
        "PixCashierv3::__AccessControlExt_init_unchained",
        "PixCashierv3::grantRoleBatch",
        "PixCashierv3::revokeRoleBatch",
        "PixCashierv3::__PausableExt_init",
        "PixCashierv3::__PausableExt_init_unchained",
        "PixCashierv3::__Rescuable_init",
        "PixCashierv3::__Rescuable_init_unchained",
        "PixCashierv3::__PixCashier_init",
        "PixCashierv3::__PixCashier_init_unchained",
        "PixCashierv4::_checkInitializing",
        "PixCashierv4::_isInitializing",
        "PixCashierv4::__Context_init",
        "PixCashierv4::__Context_init_unchained",
        "PixCashierv4::_msgSender",
        "PixCashierv4::__ERC165_init",
        "PixCashierv4::__ERC165_init_unchained",
        "PixCashierv4::__AccessControl_init",
        "PixCashierv4::__AccessControl_init_unchained",
        "PixCashierv4::grantRole",
        "PixCashierv4::revokeRole",
        "PixCashierv4::__UUPSUpgradeable_init",
        "PixCashierv4::__UUPSUpgradeable_init_unchained",
        "PixCashierv4::upgradeToAndCall",
        "PixCashierv4::_checkProxy",
        "PixCashierv4::_authorizeUpgrade",
        "PixCashierv4::__Pausable_init",
        "PixCashierv4::__Pausable_init_unchained",
        "PixCashierv4::__AccessControlExt_init",
        "PixCashierv4::__AccessControlExt_init_unchained",
        "PixCashierv4::grantRoleBatch",
        "PixCashierv4::revokeRoleBatch",
        "PixCashierv4::__PausableExt_init",
        "PixCashierv4::__PausableExt_init_unchained",
        "PixCashierv4::__Rescuable_init",
        "PixCashierv4::__Rescuable_init_unchained",
        "PixCashierv4::__PixCashier_init",
        "PixCashierv4::__PixCashier_init_unchained"
    ]
    .into_iter()
    .collect();
}
