apiVersion: v1
kind: Service
metadata:
  name: stratus-api
spec:
  selector:
    app: stratus-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
    - protocol: TCP
      port: 9000
      targetPort: 9000
