# Build
FROM rust:1.75 as builder

WORKDIR /app
COPY src /app/src
COPY static /app/static
COPY .sqlx /app/.sqlx
COPY build.rs /app/build.rs
COPY Cargo.toml /app/Cargo.toml
COPY Cargo.lock /app/Cargo.lock

RUN apt update
RUN apt-get install -y libclang-dev cmake

ENV CARGO_PROFILE_RELEASE_DEBUG=1
ENV JSON_LOGS=1
ENV NO_COLOR=1
RUN cargo build --release --bin run-with-importer --features metrics

# Runtime
FROM rust:1.75 as runtime
WORKDIR /app
COPY --from=builder /app/target/release/run-with-importer /app/run-with-importer

CMD ["sh", "-c", "/app/run-with-importer"]
