kubernetes:
  base:
    sourceRepo:
      name: stratus
      org: cloudwalk
    monoRepo:
      url: git@github.com:cloudwalk/monorepo-gitops.git
      appsFolder: apps-config
      argoCDValues: helms/argocd/values.yaml
    containerRegistry:
      url: gcr.io/infinitepay-production
    deployConfig:
      cluster: infinitepay-production
      environment: production
      steps:
        - build
        - push
        - versioning
        - deploy
      service:
        asmRevision: asm-managed-stable
  apps:
    # --------------------------------------------------------------------------
    # EVM api Rocksdb storage
    # --------------------------------------------------------------------------
    - name: stratus-api
      dockerfile: ./docker/Dockerfile.run_with_importer
      secretsManager:
        enabled: true
        provider: gcpsm
      imageRepoName: stratus-rocks
      kind: statefulset
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      replicas: 0
      resources:
        requests:
          cpu: 16000m
          memory: 32Gi
      envs:
        - name: ENV
          value: "production"
      service:
        metrics:
          path: "/"
          port: "9000"
        ports:
          - containerPort: 3000
            name: app-stratus
            virtualservice:
              gateway: internal
              hosts:
                - stratus-api.services.production.cloudwalk.network
          - containerPort: 9000
            name: metrics
      livenessProbe:
        httpGet:
          path: /liveness
          port: 3000
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /readiness
          port: 3000
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 5
      startupProbe:
        httpGet:
          path: /startup
          port: 3000
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 60
        timeoutSeconds: 5
      volumeClaims:
      - name: rocksdata
        storageClass: premium-rwo
        size: 1500Gi
      volumeMounts:
      - volumeName: rocksdata
        mountPath: /app/data
        storageClass: premium-rwo
