global:
  scrape_interval: 500ms
  scrape_timeout:  500ms

scrape_configs:
  - job_name: stratus
    metrics_path: /
    static_configs:
      - targets:
        - host.docker.internal:9000
        - 192.168.0.14:9000