name: Build Binary

on:
  workflow_dispatch:
    inputs:
      features:
        description: "List of features to enable"
        required: false
        default: ""
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "tests/fixtures/**"
      - "static/**"
      - ".sqlx/**"

env:
  RETENTION_DAYS: 90

jobs:
  build_binaries:
    name: Build and upload
    runs-on: ubuntu-latest
    timeout-minutes: 45

    concurrency:
      group: ${{ github.workflow }}-{{ github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.81

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        id: cache-cargo
        with:
          prefix-key: ${{ runner.os }}-v3-cargo
          shared-key: artifact
          cache-provider: "github"
          save-if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}

      - name: Install libsasl2-dev libssl-dev
        run: sudo apt-get update && sudo apt install -y build-essential pkg-config libssl-dev libsasl2-dev

      - name: Build default binary
        run: |
          cargo build --release \
            --bin stratus \
            --features "$FEATURES" \
            --target-dir target/default
        env:
          CARGO_PROFILE_RELEASE_DEBUG: 1
          TRACING_LOG_FORMAT: json
          NO_COLOR: 1
          FEATURES: "${{ github.event.inputs.features || 'default' }}"

      - name: Build profiling binary
        run: |
          cargo build --release \
            --bin stratus \
            --features "$FEATURES,jeprof" \
            --target-dir target/profiling
        env:
          CARGO_PROFILE_RELEASE_DEBUG: 1
          TRACING_LOG_FORMAT: json
          NO_COLOR: 1
          FEATURES: "${{ github.event.inputs.features || 'default' }}"
          RUSTFLAGS: "-C force-frame-pointers=yes"

      - name: Upload default stratus
        uses: actions/upload-artifact@v4
        id: upload-default-stratus
        with:
          name: stratus-${{ github.sha }}
          path: target/release/stratus
          if-no-files-found: error
          retention-days: ${{ env.RETENTION_DAYS }}

      - name: Upload profiling stratus
        uses: actions/upload-artifact@v4
        id: upload-profiling-stratus
        with:
          name: stratus-prof-${{ github.sha }}
          path: target/release/stratus
          if-no-files-found: error
          retention-days: ${{ env.RETENTION_DAYS }}

      - name: Print outputs
        run: |
          echo "Artifact ID: ${{ steps.upload-default-stratus.outputs.artifact-id }} (stratus)"
          echo "Artifact URL: ${{ steps.upload-default-stratus.outputs.artifact-url }} (stratus)"
          echo "Artifact ID: ${{ steps.upload-profiling-stratus.outputs.artifact-id }} (stratus-prof)"
          echo "Artifact URL: ${{ steps.upload-profiling-stratus.outputs.artifact-url }} (stratus-prof)"