name: Build Lint Cache

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "tests/fixtures/**"
      - "static/**"
      - ".sqlx/**"

env:
  CACHE_LINT_KEY: lint-nightly-2026-05-08  # gitleaks:allow - cache key, not a secret
  CACHE_PATH: |
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  build_lint_cache:
    name: Build Lint cache
    runs-on: ubuntu-22.04
    timeout-minutes: 55

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
          persist-credentials: false
      - name: Build cache internally
        uses: ./.github/actions/run-internal-ci
        with:
          internal-workflow: build-lint-cache.yml
          ref: ${{ github.sha }}
          ci-key: build-lint-cache
          timeout-minutes: 50
          token: ${{ secrets.INTERNAL_BUILDS_TOKEN }}
