name: Build PGO

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
    inputs:
      features:
        description: "List of features to enable"
        required: false
        default: ""
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "tests/fixtures/**"
      - "static/**"
      - ".sqlx/**"

env:
  RETENTION_DAYS: 90

jobs:
  build_binaries:
    name: Build and upload
    runs-on: ubuntu-22.04
    timeout-minutes: 45

    concurrency:
      group: ${{ github.workflow }}-{{ github.run_id }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.88

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        id: cache-cargo
        with:
          prefix-key: ${{ runner.os }}-v3-cargo
          shared-key: artifact
          cache-provider: "github"
          save-if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}

      - name: Install libsasl2-dev libssl-dev
        run: sudo apt-get update && sudo apt install -y build-essential pkg-config libssl-dev libsasl2-dev

      - name: Install cargo-pgo
        run: cargo install cargo-pgo

      - name: Build instrumented binary
        run: cargo pgo build -- --bin stratus --features "$FEATURES"
        env:
          CARGO_PROFILE_RELEASE_DEBUG: 1
          TRACING_LOG_FORMAT: json
          NO_COLOR: 1
          FEATURES: "${{ github.event.inputs.features || 'default' }}"

      - name: ls
        run: ls target
