name: Build Debug Cache

permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:
    inputs:
      features:
        description: "List of features to enable"
        required: false
        default: ""
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"
      - "tests/fixtures/**"
      - "static/**"
      - ".sqlx/**"

env:
  CACHE_SHARED_KEY: stable-release
  CACHE_PATH: |
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  build_debug_cache:
    name: Build Debug cache
    runs-on: ubuntu-22.04
    timeout-minutes: 130

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
          persist-credentials: false
      - name: Build cache internally
        uses: ./.github/actions/run-internal-ci
        with:
          internal-workflow: build-debug-cache.yml
          ref: ${{ github.sha }}
          ci-key: build-debug-cache
          dispatch-inputs: ${{ format('{{"features":{0}}}', toJSON(inputs.features)) }}
          timeout-minutes: 125
          token: ${{ secrets.INTERNAL_BUILDS_TOKEN }}
