name: Check Features

permissions: read-all

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "src/**"
      - ".github/workflows/check-features.yml"
      - "justfile"
      - "Cargo.toml"

  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "rust-toolchain.toml"

  workflow_dispatch:

env:
  CACHE_SHARED_KEY: stable-release
  CACHE_PATH: |
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  check_features:
    name: Check Features
    runs-on: ubuntu-22.04
    timeout-minutes: 35

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: 1.88

      - name: Rust Cache - Restore shared key
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.CACHE_PATH }}
          restore-keys: ${{ env.CACHE_SHARED_KEY }}
          key: ${{ env.CACHE_SHARED_KEY }}

      - name: Install libsasl2-dev libssl-dev
        run: sudo apt-get update && sudo apt install -y build-essential pkg-config libssl-dev libsasl2-dev

      - name: Set up Just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0

      - name: Install cargo tools
        run: cargo install killport@1.1.0 wait-service@0.3.1 cargo-hack@0.6.39

      - name: Run cargo checks
        run: just check-features
        env:
          CARGO_PROFILE_RELEASE_DEBUG: 0
          RUST_LOG: error
          RELEASE: 1
