name: Check Unused Dependencies

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "Cargo.toml"
      - "Cargo.lock"

env:
  CACHE_SHARED_KEY: stable-release
  CACHE_PATH: |
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  check_unused_deps:
    name: Check for unused dependencies
    runs-on: ubuntu-22.04
    timeout-minutes: 40

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Run internal check
        uses: ./.github/actions/run-internal-ci
        with:
          internal-workflow: check-unused-deps.yml
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          pr: ${{ github.event.pull_request.number || '' }}
          ci-key: check-unused-deps
          timeout-minutes: 35
          token: ${{ secrets.INTERNAL_BUILDS_TOKEN }}
