name: Check Features

permissions: read-all

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "src/**"
      - ".github/workflows/check-features.yml"
      - "justfile"
      - "Cargo.toml"

  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "rust-toolchain.toml"

  workflow_dispatch:

env:
  CACHE_CHECK_KEY: check-features-release
  CACHE_PATH: |
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  check_features:
    name: Check Features
    runs-on: ubuntu-22.04
    timeout-minutes: 45

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          persist-credentials: false

      - name: Run internal check
        uses: ./.github/actions/run-internal-ci
        with:
          internal-workflow: check-features.yml
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          pr: ${{ github.event.pull_request.number || '' }}
          ci-key: check-features
          timeout-minutes: 40
          token: ${{ secrets.INTERNAL_BUILDS_TOKEN }}
