name: Check Unused Dependencies

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "Cargo.toml"
      - "Cargo.lock"

env:
  CACHE_SHARED_KEY: stable-release
  CACHE_PATH: |
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/

jobs:
  check_unused_deps:
    name: Check for unused dependencies
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Rust Nightly
        uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2 # nightly
        with:
          toolchain: nightly-2025-05-22
          components: rustfmt, clippy

      - name: Rust Cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ env.CACHE_PATH }}
          restore-keys: ${{ env.CACHE_SHARED_KEY }}
          key: ${{ env.CACHE_SHARED_KEY }}

      - name: Install libsasl2-dev libssl-dev
        run: sudo apt-get update && sudo apt install -y build-essential pkg-config libssl-dev libsasl2-dev

      - name: Set up Just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0

      - name: Check for unused dependencies
        run: just check-unused-deps -2025-05-22
