name: Check Unused Dependencies

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "*"
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  check_unused_deps:
    name: Check for unused dependencies
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2025-05-22
          components: rustfmt, clippy

      - name: Install libsasl2-dev libssl-dev
        run: sudo apt-get update && sudo apt install -y build-essential pkg-config libssl-dev libsasl2-dev

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Check for unused dependencies
        run: just check-unused-deps -2025-05-22
