name: GitHub Builder

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Choose the deployment environment'
        options:
        - production
        - staging
        default: staging

jobs:
  deploy:
    uses: cloudwalk/github-builder/.github/workflows/deploy.yaml@v2
    secrets: inherit
    with:
      environment: ${{ github.event.inputs.environment }}
      config_path: config

  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ inputs.environment == 'production' }}
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Notify Slack
        run: ruby utils/slack-notifiers/outdated.rb
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_TRAIN_SLACK_WEBHOOK_URL }}
          GITHUB_SHA: ${{ github.sha }}
