name: Coverage Deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "justfile"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Build the documentation and upload as an artifact
  docs-build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download GH Pages artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Display structure of downloaded files
        run: ls -R
