name: Documentation Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'justfile'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Build the documentation and upload as an artifact
  docs-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Cargo Registry and Target Directory
        uses: actions/cache@v4.0.2
        id: cache-cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-v2-cargo-nightly-debug-${{ hashFiles('Cargo.lock', 'Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-v2-cargo-nightly-debug-
      
      - name: Set up Rust Nightly and Rust Docs
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly-2024-01-01
          rustup component add rust-docs
      
      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Generate docs
        run: |
          just doc -2024-01-01
          echo "<meta http-equiv='refresh' content='0; URL=./stratus/'>" >> target/doc/index.html
          chmod -c -R +rX target/doc/

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/doc'

  # Upload the documentation to GitHub Pages
  docs-release:
    runs-on: ubuntu-latest
    needs: docs-build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download GH Pages artifact
        uses: actions/download-artifact@v3

      - name: Configure GH Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v2