name: Contracts E2E Hybrid tests

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  contract_test_hybrid_file_changes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-changes
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check file changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            README.md
            CONTRIBUTING.md
            LICENSE
            static/contracts/*.signatures
            config/*
            .github/workflows/deploy.yml
            .github/CODEOWNERS
            .github/workflows/docs-release.yml
            .github/workflows/outdated.yml
    outputs:
      only_modified: ${{ steps.changed-files.outputs.only_modified }}
  contract_test_hybrid:
    needs: contract_test_hybrid_file_changes
    if: github.event_name != 'pull_request' || needs.contract_test_hybrid_file_changes.outputs.only_modified == 'true'
    name: Contracts E2E Hybrid Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Set up ASDF Version Manager
        uses: asdf-vm/actions/setup@v3

      - name: Install Node.js
        run: |
          asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
          asdf install nodejs 20.10.0
          asdf global nodejs 20.10.0

      - name: Set up Test and clone repositories
        run: just setup

      - name: Run e2e tests
        run: PERM_STORAGE=hybrid://postgres:123@0.0.0.0:5432/stratus just contracts-test-stratus-postgres
