name: Contracts E2E Rocks tests

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '.github/workflows/deploy.yml'
      - '.github/workflows/docs-release.yml'
      - '.github/workflows/outdated.yml'
      - '.github/workflows/comment-tag-report.yml'
      - '.github/workflows/pr-agent.yml'
      - '.github/CODEOWNERS'
      - 'config/**'
      - 'README.md'
      - 'LICENSE'
      - 'CONTRIBUTING.md'
      - 'utils/slack-notifiers/**'
  workflow_dispatch:
  push: # Rebuild cache policy
    branches:
      - 'main'
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'

jobs:
  contract_test_rocks:
    strategy:
      fail-fast: false
    name: E2E Relayer Rocks
    runs-on: ubuntu-latest
    timeout-minutes: 45

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cargo Registry and Target Directory
        uses: actions/cache@v4.0.2
        id: cache-cargo
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-v2-cargo-stable-release-${{ hashFiles('Cargo.lock', 'Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-v2-cargo-stable-release-

      - name: Set up Rust
        if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Set up ASDF Version Manager
        uses: asdf-vm/actions/setup@v3

      - name: Install Node.js
        run: |
          asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
          asdf install nodejs 20.10.0
          asdf global nodejs 20.10.0

      - name: Set up dependencies
        if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        run: |
          cargo install killport || true
          cargo install wait-service || true

      - name: Clone BRLCToken repository
        run: just contracts-clone --token

      - name: Flatten BRLCToken contract
        run: just contracts-flatten

      - name: Run e2e tests
        run: just e2e-relayer
        env:
          CARGO_PROFILE_RELEASE_DEBUG: 0 
          RUST_LOG: off 
          RELEASE: 1
