name: Contracts E2E Postgres tests

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  contract_test_psql:
    name: Contracts E2E Postgres Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Set up ASDF Version Manager
        uses: asdf-vm/actions/setup@v3

      - name: Install Node.js
        run: |
          asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
          asdf install nodejs 20.10.0
          asdf global nodejs 20.10.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
        with:
          cache-all-crates: "true"
          shared-key: ${{ runner.os }}-full

      - name: Set up Test and clone repositories
        run: just setup

      - name: Run e2e tests
        run: PERM_STORAGE=postgres://postgres:123@0.0.0.0:5432/stratus just contracts-test-stratus-postgres
