name: E2E Genesis Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - 'src/eth/genesis.rs'
      - 'src/config.rs'
      - 'e2e/test/genesis/**'
      - 'config/genesis.local.json'
      - '.github/workflows/e2e-genesis.yml'

env:
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_LOG: "info"

jobs:
  e2e-genesis:
    name: E2E Genesis Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup needed dependencies
        uses: ./.github/workflows/_setup-e2e

      - name: Environment Information
        run: |
          echo "OS: $(uname -s)"
          echo "Architecture: $(uname -m)"
          cargo --version
          rustc --version
          node --version
          npm --version

      - name: Installing killport
        run: cargo install killport

      - name: Installing wait-service
        run: cargo install wait-service
        
      - name: Build Stratus
        run: cargo build --release --bin stratus --features dev

      - name: Create e2e directories
        run: |
          mkdir -p e2e_logs
          mkdir -p e2e/config

      - name: Copy genesis file
        run: cp config/genesis.local.json e2e/config/

      - name: Start Stratus with genesis.json
        run: |
          RUST_LOG=debug ./target/release/stratus --leader --genesis-path config/genesis.local.json > e2e_logs/stratus-genesis.log &
          wait-service --tcp 0.0.0.0:8545 -t 60 -- echo "Stratus started"

      - name: Install E2E Dependencies
        run: |
          cd e2e
          npm ci

      - name: Run Genesis Tests
        run: |
          cd e2e
          npx hardhat test test/genesis/genesis.test.ts --network stratus

      - name: Kill Stratus
        if: always()
        run: |
          killport 8545 || true
          sleep 5
          
      - name: Clean up
        if: always()
        run: |
          rm -f e2e/config/genesis.local.json
          
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-genesis-logs
          path: e2e_logs/
          retention-days: 7 