name: Contracts E2E Rocks tests

permissions:
  contents: read

on:
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - ".github/workflows/deploy.yml"
      - ".github/workflows/docs-release.yml"
      - ".github/workflows/outdated.yml"
      - ".github/workflows/comment-tag-report.yml"
      - ".github/workflows/pr-agent.yml"
      - ".github/workflows/build-binary.yml"
      - ".github/CODEOWNERS"
      - "config/**"
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "utils/slack-notifiers/**"
  workflow_dispatch:
  push: # Rebuild cache policy
    branches:
      - "main"
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "rust-toolchain.toml"

env:
  CACHE_SHARED_KEY: stable-release
  CACHE_KEY_CONTEXT: v4-cargo-contracts-tests
  CARGO_TOOLS_CACHE_KEY: cargo-tools-v4
  CARGO_TOOLS_CACHE_PATH: ~/.cargo/bin
  CACHE_PATH: |
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/
  CACHE_KEY: ${ CACHE_KEY_CONTEXT }

jobs:
  setup_cache:
    name: Setup Cache for E2E Rocks tests
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate and set cache key
        id: cache-key
        run: |
          CACHE_KEY="${{ runner.os }}-${{ env.CACHE_KEY_CONTEXT }}-${{ hashFiles('**/Cargo.lock') }}"
          echo "CACHE_KEY=$CACHE_KEY" >> $GITHUB_ENV
          echo "key=$CACHE_KEY" >> $GITHUB_OUTPUT

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88      

      - name: Rust Cache - Restore workflow cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ env.CACHE_KEY }}
          restore-keys: ${{ env.CACHE_SHARED_KEY }}

      - name: Debug cache key
        run: echo "CACHE_KEY=$CACHE_KEY"

      - name: Install libsasl2-dev libssl-dev
        run: sudo apt-get update && sudo apt install -y build-essential pkg-config libssl-dev libsasl2-dev

      - name: Build all dependencies to prime the cache
        run: cargo build --release --locked
      
      - name: Rust Cache - Save workflow cache
        uses: actions/cache/save@v4
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}
        
      - name: Install cargo tools
        run: cargo install killport@1.1.0 wait-service@0.3.1

      - name: Rust Cache - Save cargo tools cache
        uses: actions/cache/save@v4
        with:
          key: ${{ env.CARGO_TOOLS_CACHE_KEY }}
          path: ${{ env.CARGO_TOOLS_CACHE_PATH }}

  contract_test_rocks:
    strategy:
      fail-fast: false
      matrix:
        contract: [token, pix, periphery, compound, yield, multisig, cppv2, capybara-finance, credit-agent]
    name: E2E Rocks on ${{ matrix.contract }}
    needs: setup_cache
    runs-on: ubuntu-22.04
    timeout-minutes: 45

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.contract }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.88

      - name: Rust Restore Cache
        id: cache-cargo
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.setup_cache.outputs.cache-key }}
          path: ${{ env.CACHE_PATH }}

      - name: Install libsasl2-dev libssl-dev
        run: sudo apt-get update && sudo apt install -y build-essential pkg-config libssl-dev libsasl2-dev

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      - name: Install npm
        run: npm install -g npm@10.8.2

      - name: Restore cargo tools cache
        id: cache-cargo-tools
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.CARGO_TOOLS_CACHE_PATH }}
          key: ${{ env.CARGO_TOOLS_CACHE_KEY }}

      - name: Install cargo tools
        if: steps.cache-cargo-tools.outputs.cache-hit != 'true'
        run: cargo install killport@1.1.0 wait-service@0.3.1

      - name: Set up dependencies
        # if: ${{ steps.cache-cargo.outputs.cache-hit != 'true' }}
        uses: taiki-e/install-action@v2
        with:
          tool: |
            cargo-llvm-cov@0.6.14

      - name: Clone ${{ matrix.contract }} repository
        run: just contracts-clone --${{ matrix.contract }}

      - name: Run e2e tests
        run: just run-test contracts-test-stratus --${{ matrix.contract }}
        env:
          CARGO_PROFILE_RELEASE_DEBUG: 0
          RUST_LOG: error
          RELEASE: 1
          RUST_BACKTRACE: 1

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: target/llvm-cov/codecov/contracts-test-stratus.info
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: contracts-rocks-${{ matrix.group }}
          name: contracts-rocks-${{ matrix.group }}
