name: Contracts E2E Postgres tests

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  contract_test_psql:
    strategy:
      fail-fast: false
      matrix:
        contract: [token, pix, periphery, compound, yield, multisig]
    name: ${{ matrix.contract }}
    runs-on: ubuntu-latest
    timeout-minutes: 45

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.contract }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cargo Registry and Target Directory
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ github.workflow }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ github.workflow }}

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Set up ASDF Version Manager
        uses: asdf-vm/actions/setup@v3

      - name: Install Node.js
        run: |
          asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
          asdf install nodejs 20.10.0
          asdf global nodejs 20.10.0

      - name: Set up Test and clone repositories
        run: |
          cargo install killport || true
          cargo install wait-service || true
          just contracts-clone --${{ matrix.contract }}

      - name: Run e2e tests
        run: PERM_STORAGE=postgres://postgres:123@0.0.0.0:5432/stratus just contracts-test-stratus-postgres --${{ matrix.contract }}
