name: Integration Tests

on:
  # pull_request:
  #   branches:
  #     - '*'
  #   paths-ignore:
  #     - '.github/workflows/deploy.yml'
  #     - '.github/workflows/docs-release.yml'
  #     - '.github/workflows/outdated.yml'
  #     - '.github/workflows/comment-tag-report.yml'
  #     - '.github/workflows/pr-agent.yml'
  #     - '.github/CODEOWNERS'
  #     - 'config/**'
  #     - 'README.md'
  #     - 'LICENSE'
  #     - 'CONTRIBUTING.md'
  #     - 'utils/slack-notifiers/**'
  workflow_dispatch:
  # push: # Rebuild cache policy
  #   branches:
  #     - 'main'
  #   paths:
  #     - 'Cargo.lock'
  #     - 'Cargo.toml'

jobs:
  int_tests:
    if: ${{ github.event_name == 'workflow_dispatch' }} # Defensive programming
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.79

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        id: cache-cargo
        with:
          prefix-key: ${{ runner.os }}-v3-cargo
          shared-key: test
          key: ${{ hashFiles('Cargo.lock', 'Cargo.toml') }}
          cache-provider: "github"
          cache-directories: "~/.cargo/bin/"

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Integration tests
        run: just test-int
