name: Integration Tests

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  int_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cargo Registry and Target Directory
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ github.workflow }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ github.workflow }}

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Integration tests
        run: just test-int