name: Integration Tests

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  unit_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Integration tests
        run: just test-int