name: Check Outdated

on:
    schedule:
        - cron: "0 7 * * *"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    outdated:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Rust
              run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

            - name: Install protobuf compiler
              run: sudo apt-get install -y protobuf-compiler

            - name: Set up Just
              uses: extractions/setup-just@v1

            - name: Check outdated
              run: just outdated > outdated.txt

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1
              with:
                ruby-version: '3.2.2'

            - name: Notify Slack
              run: ruby utils/slack-notifiers/outdated.rb
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.STRATUS_SLACK_WEBHOOK_URL }}
                  OUTDATED_TABLE_FILE_NAME: outdated.txt
