name: Check Outdated

on:
    schedule:
        - cron: "0 7 * * *"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    outdated:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Rust
              run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y    
            
            - name: Set up Just
              uses: extractions/setup-just@v1

            - name: Check outdated
              run: just outdated | tee outdated.txt

              # Loads from text file, escapes newlines and quotes and build message
            - name: Build Message
              id: outdated
              run: |
                TABLE="$(cat outdated.txt)"
                TABLE="${TABLE//$'\n'/\\n}"
                TABLE="${TABLE//\"/\\\"}"
                MESSAGE="Stratus outdated crates:\\n\\n\`\`\`${TABLE}\`\`\`"
                echo "message=$MESSAGE" >> $GITHUB_ENV 

            - name: Notify Slack
              id: slack
              uses: slackapi/slack-github-action@v1.26.0
              with:
                payload: |
                  {
                    "text": "${{ env.message }}",
                  }
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.STRATUS_SLACK_WEBHOOK_URL }}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK