name: Check Outdated

on:
    schedule:
        - cron: "0 7 * * *"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: true

jobs:
    outdated:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Rust
              run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y    
            
            - name: Set up Just
              uses: extractions/setup-just@v1

            - name: Check outdated
              run: just outdated

