name: Unit Tests

on:
  pull_request:
    branches:
      - '*'

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Unit tests
        run: just test-unit