name: Unit Tests

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  unit_tests_file_changes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-changes
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check file changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            README.md
            CONTRIBUTING.md
            LICENSE
            static/contracts/*.signatures
            config/*
            .github/workflows/deploy.yml
            .github/CODEOWNERS
            .github/workflows/docs-release.yml
            .github/workflows/outdated.yml
    outputs:
      only_modified: ${{ steps.changed-files.outputs.only_modified }}
      
  unit_tests:
    needs: unit_tests_file_changes
    if: ${{ needs.unit_tests_file_changes.outputs.only_modified == 'true' }}
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Cargo Registry and Target Directory
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ github.workflow }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ github.workflow }}

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Unit tests
        run: just test-unit